name: "Deploy Project"
on: [push, workflow_dispatch]
jobs:
  Lint_Test_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{toJSON(github.event)}}"
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run Test
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Deploy Project"
        run: echo "Deploying..."

